name: destacable_inc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  connectivity_plus: ^6.1.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.10
  flutter_bloc: ^8.1.6
  meta: ^1.15.0
  path: ^1.9.0
  sqflite: ^2.4.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.otf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.otf
          style: italic
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-Light.otf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.otf
          style: italic
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.otf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Italic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.otf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.otf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Bold.otf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.otf
          style: italic
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Bold.otf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.otf
          style: italic
          weight: 900